CREATE DATABASE IF NOT EXISTS CHATROOM;
CREATE TABLE IF NOT EXISTS CHATROOM.users
(
  userid VARCHAR(32) NOT NULL PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  passwords VARCHAR(50) NOT NULL,
  createtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modifytime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  isdelete TINYINT NOT NULL DEFAULT 0
);

CREATE OR REPLACE VIEW CHATROOM.usinguser AS 
SELECT userid, username, passwords, createtime, modifytime FROM CHATROOM.users WHERE isdelete = 0;

CREATE TABLE IF NOT EXISTS CHATROOM.groups
(
  groupid BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  groupname VARCHAR(50) NOT NULL,
  createtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modifytime TIMESTAMP NOT NULL,
  createperson BIGINT NOT NULL,
  deletetime TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS CHATROOM.groups_user_relation
(
  relationid BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  groupid BIGINT NOT NULL,
  createperson BIGINT NOT NULL,
  nickname VARCHAR(50) NOT NULL,
  createtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modifytime TIMESTAMP NOT NULL,
  deletetime TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS CHATROOM.groups_message
(
  messageid BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  groupid BIGINT NOT NULL,
  createperson BIGINT NOT NULL,
  nickname VARCHAR(50) NOT NULL,
  createtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modifytime TIMESTAMP NOT NULL,
  deletetime TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS CHATROOM.user_user_message
(
  messageid BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  sendperson BIGINT NOT NULL,
  receiveperson BIGINT NOT NULL,
  createtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modifytime TIMESTAMP NOT NULL,
  deletetime TIMESTAMP NOT NULL
);
