CREATE DATABASE CHATROOM;
CREATE TABLE CHATROOM.users
(
  userid BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL,
  passwords VARCHAR(50) NOT NULL,
  createtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modifytime TIMESTAMP NOT NULL,
  deletetime TIMESTAMP NOT NULL
);

CREATE TABLE CHATROOM.groups
(
  groupid BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  groupname VARCHAR(50) NOT NULL,
  createtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modifytime TIMESTAMP NOT NULL,
  createperson BIGINT NOT NULL,
  deletetime TIMESTAMP NOT NULL
);

CREATE TABLE CHATROOM.groups_user_relation
(
  relationid BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  groupid BIGINT NOT NULL,
  createperson BIGINT NOT NULL,
  nickname VARCHAR(50) NOT NULL,
  createtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modifytime TIMESTAMP NOT NULL,
  deletetime TIMESTAMP NOT NULL
);

CREATE TABLE CHATROOM.groups_message
(
  messageid BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  groupid BIGINT NOT NULL,
  createperson BIGINT NOT NULL,
  nickname VARCHAR(50) NOT NULL,
  createtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modifytime TIMESTAMP NOT NULL,
  deletetime TIMESTAMP NOT NULL
);

CREATE TABLE CHATROOM.user_user_message
(
  messageid BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  sendperson BIGINT NOT NULL,
  receiveperson BIGINT NOT NULL,
  createtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modifytime TIMESTAMP NOT NULL,
  deletetime TIMESTAMP NOT NULL
);
